apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: codegen-demo-0510
  janus-idp.io/tekton: codegen-demo-0510
  backstage.io/kubernetes-id: codegen-demo-0510
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: codegen-demo-0510
resources:
- deployment.yaml
- route.yaml
- service.yaml
